# Generated by Django 3.2.9 on 2021-12-02 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_conso', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compte',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
