# Generated by Django 3.2.9 on 2021-12-15 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_conso', '0002_compte_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='compte',
            name='connecte',
            field=models.BooleanField(null=True),
        ),
    ]
