# Generated by Django 3.2.9 on 2021-12-15 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_conso', '0003_compte_connecte'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('champ', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PDL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('champ', models.CharField(max_length=255)),
            ],
        ),
    ]
