# Generated by Django 3.2.9 on 2021-12-15 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_conso', '0005_compte_email_verifie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compte',
            name='email_verifie',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
