# Generated by Selenium IDE
from os import sep
from tkinter.ttk import Separator
import pandas as pd
import os



file = pd.read_csv(r"C:\data\Timeseries_43.562_1.463_SA_45deg_0deg_2015_2015 (2).csv",on_bad_lines='skip',skiprows=8,skipfooter=10)
file = file.drop(columns=['G(i)','T2m','WS10m','Int'],axis = 1)
file = file.sort_values('time')
list1prod = file['time'].to_list()
for i in range(len(list1prod)) :
    list1prod[i] = list1prod[i].split(":")[0]+":"+list1prod[i].split(":")[1][0]+list1prod[i].split(":")[1][1]+"00"
l = []
for i in range(len(list1prod)) : 
    l.append(list1prod[i])
        l.append(list1prod[0][0:9]+str())
print(list1prod[0][0:9])
